# Generated by Django 3.2.8 on 2022-06-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_textinformation_input_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textinformation',
            name='input_text',
            field=models.CharField(max_length=100),
        ),
    ]
